#!/usr/bin/env bash

DBPATH="$(dirname `readlink -m $0`)/../data"     # Or replace by absolute path to persistence DB directory

# Uncomment and specify to use your own wallabag codebase
# SOURCEPATH='/home/bob/Work/wallabag'           # Absolute path to wallabag sources

# Uncomment and specify to use your own wallabag SALT value in config file
SALT='34gAogagAigJaurgbqfdvqQergvqer'            # No space in this string please

IMAGENAME='bobmaerten/docker-wallabag:latest'

WALLABAGSOURCE='wallabag-source'
WALLABAGDB='wallabag-db'
WALLABAG='wallabag-server'

function setup() {
    mkdir -p $DBPATH
    echo "#Exporting db from the container to host, in $DBPATH"
    ID=$(sudo docker run -d $IMAGENAME /sbin/my_init --skip-startup-files --quiet)
    sudo docker cp $ID:/var/www/wallabag/db/poche.sqlite $DBPATH
    sudo chown -R $USER:$USER $DBPATH
    sudo chmod -R 777 $DBPATH
    ID=$(sudo docker stop $ID)
    ID=$(sudo docker rm $ID)
}

function getStatus(){
    CONTAINER_ID=$(sudo docker ps -a | grep -v Exit | grep $WALLABAG | awk '{print $1}')
    if [ -z $CONTAINER_ID ] ; then
        echo 'Not running.'
        return 1
    else
        URL=$(sudo docker port $CONTAINER_ID 80)
        IP=$(sudo docker inspect --format '{{ .NetworkSettings.IPAddress }}' $CONTAINER_ID)
        echo "Running in container: $CONTAINER_ID"
        echo "IP address: $IP"
        echo "Web server on http://$URL"
        return 0
    fi
}

case "$1" in
    start)
        if [ ! -f $DBPATH/poche.sqlite ] ; then
            setup
        fi

        VOLUMES=''
        sudo docker ps -a | grep -q $WALLABAGDB
        if [ $? -ne 0 ]; then
            sudo docker run --name $WALLABAGDB -v $DBPATH:/var/www/wallabag/db ubuntu true
            VOLUMES="--volumes-from $WALLABAGDB"
        fi

        if [ -n "$SOURCEPATH" ]; then
            sudo docker ps -a | grep -q $WALLABAGSOURCE
            if [ $? -ne 0 ]; then
                sudo docker run --name $WALLABAGSOURCE -v $SOURCEPATH:/var/www/wallabag ubuntu true
                VOLUMES="--volumes-from $WALLABAGSOURCE $VOLUMES"
            fi
        fi

        if [ -n "$SALT" ]; then
            WALLABAG_ENV="--env WALLABAG_SALT=$SALT"
        fi
        sudo docker ps -a | grep -v Exit | grep -q $WALLABAG
        if [ $? -ne 0 ]; then
            CONTAINER_ID=$(sudo docker run $WALLABAG_ENV -d --name $WALLABAG $VOLUMES -p=8080:80 $IMAGENAME /sbin/my_init --enable-insecure-key)
        fi
        getStatus
        ;;

    status)
        getStatus
        ;;

    stop)
        CONTAINER_ID=$(sudo docker ps -a | grep -v Exit | grep $WALLABAG | awk '{print $1}')
        if [[ -n $CONTAINER_ID ]] ; then
            SV=$(sudo docker stop $CONTAINER_ID)
            SV=$(sudo docker rm $CONTAINER_ID)
            if [ $? -eq 0 ] ; then
                echo 'Stopped.'
                DB=$(sudo docker ps -a | grep $WALLABAGDB | awk '{print $1}')
                DB=$(sudo docker rm $DB)
                if [ -n "$SOURCEPATH" ]; then
                    SRC=$(sudo docker ps -a | grep $WALLABAGSOURCE | awk '{print $1}')
                    SRC=$(sudo docker rm $SRC)
                fi
            fi
        else
            echo 'Not running.'
            exit 1
        fi
        ;;

    *)
        echo "Usage: `basename $0` {start|stop|status}"
        exit 1
        ;;
esac

exit 0
